# Generated by Django 3.1.1 on 2020-09-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalbudget', '0001_created_half_models_personal_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
